name: Spring-Docker Release workflow
on:
  pull_request:
    branches: master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
 
## It will generate by default, which is similar to Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.rankilla20.springdocker.SpringDockerApplication]      
    - name: kubectl - Google Cloud GKE cluster.
      # You may pin to the exact commit or the version.
      # uses: ameydev/gke-kubectl-action@dbe114f1703050edcbdc4285cab3f859646834d2
      uses: ameydev/gke-kubectl-action@v1.02
      with:
        # GCP authorization credentials
        APPLICATION_CREDENTIALS: ${{ secrets.G_APPLICATION_CREDENTIALS }}
        # Project id
        PROJECT_ID: ${{ secrets.G_PROJECT_ID }}
        # GKE Cluser Name
        CLUSTER_NAME: ${{ secrets.G_CLUSTER_NAME }}
        # Zone Name
        ZONE_NAME: ${{ secrets.G_ZONE_NAME }}
    - name: List directories
      run: ls -ltr
