name: Spring-Docker Release workflow
env:
    appName: ';
on:
  pull_request:
    branches: master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Configure git
      run: |
        git config --global committer.email "raju.ankilla@gmail.com"
        git config --global committer.name "Raji Ankilla"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"
    - name: Checkout master branch
      run: git checkout master
    - name: Generate build number 
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }} 
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - name: Set repository name
      run: echo ::set-env name=REPOSITORY_NAME::${GITHUB_REPOSITORY#*/}-${GITHUB_SHA:0:7}
    - name: Print repo name
      run: echo "Repository name is $REPOSITORY_NAME
    - name: Login to  DockerHub
      uses: docker/login-action@v1
      with:
        username: $ {{secrets.MY_DOCKER_HUB_USERNAME}}
        password: ${{secrets.MY_DOCKER_HUB_TOKEN}}
    - name: Check images
      run: docker images
